name: fin_track
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  lottie: ^1.3.0
  another_flushbar: ^1.10.28
  page_transition: ^2.0.5
  simple_gesture_detector: ^0.2.0
  shared_preferences: ^2.0.13
  get: ^4.6.1
  badges: ^3.1.1
  http: ^0.13.4
  flutter_overlay_loader: ^1.0.3
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  syncfusion_flutter_xlsio: ^20.1.52-beta
  path_provider: ^2.0.9
  share_plus: ^4.0.4
  image_picker: ^0.8.5
  flutter_staggered_grid_view: ^0.6.1
  percent_indicator: ^4.0.1
  flutter_local_notifications: ^9.5.3+1
  easy_image_viewer: ^1.0.4
  timezone: ^0.8.0
  pie_chart: ^5.3.0
  scrollable_positioned_list: any
  screenshot: ^2.1.0
  transparent_image: ^2.0.0
  flutter_contacts: ^1.1.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/other/
    - assets/images/avatars/
    - assets/images/incomes/
    - assets/images/expenses/
    - assets/images/paymodes/
    - assets/images/goals/
    - assets/images/custom/
    - assets/images/groups/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.otf
          weight: 900
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 400
        - asset: assets/fonts/CircularStd-Book.otf
          weight: 300
        - asset: assets/fonts/CircularStd-Light.otf
          weight: 100

